name: Grype Vulnerability Scanner

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
            path: "."