name: SBOM generation

on: push

permissions:
  contents: read
  issues: write

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install Syft
        run: |
          curl -sSL https://github.com/anchore/syft/releases/latest/download/syft_$(uname -s)_$(uname -m).tar.gz | tar -xz -C /usr/local/bin
          chmod +x /usr/local/bin/syft
      - name: Run Syft
        run: |
        syft . -o spdx-json --file sbom.syft.yaml