name: Lint Code Base

on:
  push:
    branches:
    - main
jobs:
  run-lint:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: $default-branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
