name: Zip and Push Lambda Functions

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  zip_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Zip Lambda Functions
        run: |
          LAMBDA_DIR="AWS/lambda"
          ZIP_DIR="$LAMBDA_DIR/zipped"
          mkdir -p "$ZIP_DIR"
          for function in "$LAMBDA_DIR"/*; do
            if [ -d "$function" ]; then
              function_name=$(basename "$function")
              zip_file="$ZIP_DIR/$function_name.zip"
              zip -r "$zip_file" "$function"/*
              echo "Zipped $function_name to $zip_file"
            fi
          done

      - name: Configure Git for Signed Commits
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git config --local commit.gpgSign true
          git config --local user.signingkey ${{ secrets.GPG_KEY_ID }}

      - name: Commit and Push Zipped Files
        run: |
          git add AWS/lambda/zipped/*.zip
          git commit -S -m "Automated: Add zipped Lambda function code" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
